# Generated by Django 4.0.6 on 2022-07-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='identity',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
